config/routes.rb
Djsmiley0LourdBshaibuMattyhkFinal::Application.routes.draw do
  
  resources :rushees do
    member do
      post :upVote
      post :removeVote
      post :meet
      post :unmeet
      get  :getApproval
    end
  end
  resources :actions
  resources :events

  root :to => "rushees#index"
  
  post "rushees/comment" => "rushees#comment"
  post "events/addRushee" => "events#addRushee"

  get "accounts/" => "accounts#index"
  get "accounts/detail/:id" => "accounts#detail"
  get "accounts/verify/:id" => "accounts#verify" 
  get "accounts/deny/:id" => "accounts#deny" 
  get "accounts/invite"
  post "accounts/invite" => "accounts#processInvite"
  devise_for :brothers

  match '/presentation', to: 'rushees#present', via: 'get'

  

end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to	:fraternity
	has_many :attendances, dependent: :destroy
	has_many :rushees, through: :attendances

  validates :date, presence: true
  validates :name, presence: true

    def self.findAllByFraternityID fraternity_id
      return self.where :fraternity_id => fraternity_id
    end

    def addRushee(rushee)
      Attendance.create(event_id: self.id, rushee_id: rushee.id)
    end

    def nonAttendingRushees
      attendingRushees = Array.new
      self.fraternity.rushees.each do |rushee|
        attendingRushees.push(rushee)
      end
      self.attendances.each do |attendance|
        rushee = Rushee.find(attendance.rushee_id)
        attendingRushees.delete(rushee)
      end
      return attendingRushees
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_brother!
  before_filter :is_verified!
  
  def index
    @events = current_brother.fraternity.events
  end

  def new
    if !current_brother.is_admin
      redirect_to events_path, alert: 'Only admins may create events'
    end

    @event = Event.new
  end

  def create
    if !current_brother.is_admin
      redirect_to events_path, alert: 'Only admins may create events'
    end

    @event = Event.new(event_params)

    if @event.save(event_params)
      redirect_to events_path, alert: 'Event was succesfully created'
    else
      redirect_to events_path, alert: 'Event was not succesfully created'
    end
  end

  def show
    @event = Event.find(params[:id])
    @rushees = @event.rushees
    @attendance = Attendance.new
  end

  # Add a given rushee by name or email
  def addRushee
    @event = Event.find(params[:event_id])
    rushee = Rushee.find(params[:attendance][:rushee_id])
    @event.addRushee(rushee)
    redirect_to event_path(@event), alert: 'Rushee was added'
    
    rescue ActiveRecord::RecordNotFound
      redirect_to event_path(@event), alert: 'No Rushee was specified'

  end

  def edit
    if !current_brother.is_admin
      redirect_to events_path, alert: "Only admins may edit events"
      return
    else
      @event = Event.find(params[:id])
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, alert: "Event Information Updated"
    else
      redirect_to @event, alert: "Event Information was not Updated"
    end

  end

  def destroy
    @event = Event.find(params[:id])
    if current_brother.is_admin
      @event.destroy
      redirect_to events_path
    end
  end
  
  private 

  def event_params
    params.require(:event).permit(:name, :date, :fraternity_id)
  end

  def is_verified!
    if !current_brother.is_verified    
      sign_out current_brother
      redirect_to :root
      return
    end
  end

end

app/views/events/_form_add_rushee.html.erb
<%= form_tag(action: :addRushee, method: "post", class: "form-horizontal") do %>
  <%= hidden_field_tag :event_id, @event.id %>
  <%= label_tag :attendance, "Rushee: " %> 
  <%= collection_select(:attendance, :rushee_id, @event.nonAttendingRushees, :id, :full_name, include_blank: true) %>
<br>
<br>

  <div class="actions">
    <%= submit_tag("Add Rushee") %>
  </div>

<% end %>

app/views/events/_form_edit.html.erb
<%= form_for @event, :html => {:class => "form-horizontal"} do |f| %>

  <%= render 'shared/event_error_messages' %>
  <%= f.hidden_field :fraternity_id, :value => current_brother.fraternity_id %>
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Name of Event" %>
  <%= f.date_field :date, :class => 'form-control', :placeholder => "dd/mm/yyyy" %>

  <br>
  
  <div class="actions">
    <%= f.submit :class => "btn"%>
  </div>

<% end %> 

app/views/events/_form_new.html.erb
<%= form_for @event, :html => {:class => "form-horizontal"} do |f| %>

  <%= render 'shared/event_error_messages' %>
  <%= f.hidden_field :fraternity_id, :value => current_brother.fraternity_id %>
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Name of Event" %>
  <%= f.date_field :date, :class => 'form-control', :placeholder => "dd/mm/yyyy" %>

  <br>
  
  <div class="actions">
    <%= f.submit :class => "btn"%>
  </div>

<% end %> 

app/views/events/edit.html.erb
<h1 class>Editing an Event!</h1>
<div class="form-container">
  <%= render 'form_edit' %>
</div>

app/views/events/index.html.erb
<% if flash[:alert] %>
  <h2 class="flash-notice"><%= flash[:alert] %></h2>
<% end %>
<%= yield %>

<h1>Your Frat's Events</h1>

<% if @events.length > 0 %>
  <table class ="table">
    <tr>
    </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to "#{event.name}", event_path(event) %></td>
        <td><%= event.date.strftime("%d-%m-%Y") %></td>
        <% if current_brother.is_admin %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Delete', event, :method => :delete, :title => "Delete Event", data: {confirm: "Delete Event?"} %></td>
        <% end %>
      </tr>

    <% end %>
  </table>
<% else %>
  <p>Your frat doesn't have any events.</p>
<% end %>

<% if current_brother.is_admin %>
  <ul>
    <%= link_to 'Create New Event', new_event_path %> 
  </ul>
<% end %>

app/views/events/new.html.erb
<h1 class>A New Event!</h1>
<div class="form-container">
  <%= render 'form_new' %>
</div>

app/views/events/show.html.erb
<% if flash[:alert] %>
  <h2 class="flash-notice"><%= flash[:alert] %></h2>
<% end %>
<%= yield %>
<h1><%= @event.name%></h1>
<h3>Event Date: <%= @event.date.strftime("%d-%m-%Y") %></h3>

<h3>Attending Rushees:</h3>
<ul>
  <% if @rushees %>
    <% @rushees.each do |rushee| %>
      <li><%= link_to rushee.firstname + " " + rushee.lastname, rushee_path(rushee) %></li>
    <% end %>
  <% end %>
</ul>

<br>

<%= render 'form_add_rushee' %>