config/routes.rb
Djsmiley0LourdBshaibuMattyhkFinal::Application.routes.draw do
  
  resources :rushees do
    member do
      post :upVote
      post :removeVote
      post :meet
      post :unmeet
      get  :getApproval
    end
  end
  resources :actions
  resources :events

  root :to => "rushees#index"
  
  post "rushees/comment" => "rushees#comment"
  post "events/addRushee" => "events#addRushee"

  get "accounts/" => "accounts#index"
  get "accounts/detail/:id" => "accounts#detail"
  get "accounts/verify/:id" => "accounts#verify" 
  get "accounts/deny/:id" => "accounts#deny" 
  get "accounts/invite"
  post "accounts/invite" => "accounts#processInvite"
  devise_for :brothers

  match '/presentation', to: 'rushees#present', via: 'get'

  

end

app/models/rushee.rb
class Rushee < ActiveRecord::Base

	belongs_to :fraternity
	belongs_to :primary_contact, class_name: "Brother"
	has_many :attendances, dependent: :destroy
	has_many :events, through: :attendances, order: 'date desc'
	has_many :actions, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :approvals, dependent: :destroy


  validates :email, uniqueness: true, case_sensitive: false, allow_blank: true
  validates :cellphone, uniqueness: true, allow_blank: true
  validates :firstname, presence: true

  def self.findAllByPrimaryContactID id
    self.where :primary_contact_id => id
  end

  # Associates the :picture attribute with an attached file
  has_attached_file :picture, styles: {
	    thumb: '100x100>',
	    square: '200x200#',
	    medium: '300x300>'
	  }

  def assignedBrother
    if self.brother
      brother.firstname + " "+ brother.lastname
    else
      "Unassigned"
    end
  end

  def brother_approval b_id
    self.approvals.find_by brother_id: b_id
  end

  def validActionSelectStatuses
    return [["None", "None"], ["Stay the Course", "Stay the Course"], 
      ["Push Harder", "Push Harder"], ["Repudiate", "Repudiate"]]
  end

  def validBidSelectStatuses
    return [["None", "None"], ["Offered", "Offered"], ["Accepted", "Accepted"], ["Rejected", "Rejected"]]
  end

  def validActionStatuses
    return ["None", "Stay the Course", "Push Harder", "Repudiate"]
  end

  def validBidStatuses
    return ["None", "Offered", "Accepted", "Rejected"]
  end

  ##Methods to Get Full Names
  def primaryContactName
    if primary_contact
      primary_contact.full_name
    else
      "Unassigned"
    end
  end

  def fullName
    firstname + " " + lastname
  end

  # Assumes the name is given is the full name
  def self.findByName(name)
    firstName = name.split()[0]
    lastName = name.split()[1]
    return Rushee.find_by(firstname: firstName, lastname: lastName)
  end

  def self.findByEmail(email)
    return Rushee.find_by(email: email)
  end

  #Get Facebook Image URL
  def facebookProfilePicURL
    #   https://www.facebook.com/user_name
    if facebook_url
      return "https://graph.facebook.com/[PROFILE_ID]/picture"
    else
      None
    end
  end

  ##Get Approval Counts
  def metBrotherCount
    self.approvals.where(met: true).count
  end

  def upVoteCount
    self.approvals.where(vote: true).count
  end

  def full_name
    self.firstname + " " + self.lastname
  end

end

app/controllers/rushees_controller.rb
class RusheesController < ApplicationController

  layout 'application', except: :present
	before_filter :authenticate_brother!
  before_filter :is_verified!
  before_action :set_rushee, only: [:show, :edit, :update, :destroy, :upVote, :removeVote, :meet, :unmeet, :getApproval]
    #except: [:index, :new, :present, :create]

	def index
    @rushees = current_brother.fraternity.rushees
    @actions = Action.where( brother_id: current_brother.id ).order(:created_at)
    @max_feed = 5  
	end

	def show
		@comments = @rushee.comments
	end

	def new
		@rushee = Rushee.new
		@brothers = current_brother.fraternity.brothers
	end

	def create
		@rushee = Rushee.new(rushee_params)
		respond_to do |format|
			if @rushee.save(rushee_params)
				format.html { redirect_to @rushee, notice: 'Rushee was successfully created.' }
				format.json { render action: 'show', status: :created, location: @rushee }

        action = Action.new
        action.brother_id = @rushee.primary_contact_id
        action.rushee_id = @rushee.id 
        action.date = Time.now
        action.description = "You're a primary contact for " + @rushee.fullName + "."
        action.save()
			else
				format.html { render action: 'new' }
				format.json { render json: @rushee.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	def delete
	end

  def update
    send_reminder = false
    old_bro = @rushee.primary_contact_id
    new_bro = params[:rushee][:primary_contact_id]
    if old_bro != new_bro
      send_reminder = true
    end

    respond_to do |format|
      if @rushee.update(rushee_params)
        format.html { redirect_to @rushee, notice: 'Rushee was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @rushee }

        if send_reminder
          # create action for whoever gets the rushee 
          action = Action.new
          action.brother_id = new_bro
          action.rushee_id = @rushee.id 
          action.date = Time.now
          action.description = "You're a primary contact for " + @rushee.fullName + "."
          action.save()

          # notify the other guy that the rushee doesn't belong to him anymore
          action2 = Action.new
          action2.brother_id = old_bro
          action2.rushee_id = @rushee.id
          action2.date = Time.now
          action2.description = "You are no longer primary contact for " + @rushee.fullName + "."
          action2.save()
        end

      else
        format.html { render action: 'new' }
        format.json { render json: @rushee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_brother.is_admin 
      @rushee.destroy
      redirect_to rushees_path
    end
  end
  
  # Comment Related Methods
  def comment
    comment = Comment.new
    comment.rushee_id = params[:id]
    comment.brother_id = current_brother.id
    comment.text = params[:text]
    comment.save
    
    redirect_to "/rushees/"+comment.rushee_id.to_s
  end

  def commentDestroy
  	@comment = Comment.find(params[:comment_id])
  	@comment.destroy
  end

  #Presentation View
  def present
    @rushees = current_brother.fraternity.rushees
    respond_to do |format|
      format.html { render :layout => false }
      format.json { render json: @rushees }
    end
  end

  #Actions to Change Vote and Met Brother Counts
  def upVote
    current_brother.upVote(@rushee)
    redirect_to :back
  end

  def removeVote
    current_brother.removeVote(@rushee)
    redirect_to :back
  end

  def meet
    current_brother.meet(@rushee)
    redirect_to :back
  end

  def unmeet
    current_brother.unmeet(@rushee)
    redirect_to :back
  end

  def getApproval
    if current_brother.approvals.where(rushee: @rushee).exists?
      @approval = current_brother.approvals.where(rushee: @rushee)  
    else
      current_brother.unmeet(@rushee)
      @approval = current_brother.approvals.where(rushee: @rushee)
    end
    render json: @approval
  end

  #Helper Functions

	private
	# Never trust parameters from the scary internet, only allow the white list through.
  def rushee_params
    params.require(:rushee).permit(:firstname, :lastname, :email, :cellphone, 
    	:facebook_url, :twitter_url, :picture, :dorm, :room_number, 
    	:hometown, :sports, :frats_rushing, :primary_contact_id, :fraternity_id,
    	:action_status, :bid_status)
  end

	# Use callbacks to share common setup or constraints between actions.
	def set_rushee
	  @rushee = Rushee.find(params[:id])
	end
         
  def is_verified!
    if !current_brother.is_verified    
      sign_out current_brother
      flash[:error] = "Your account has not been verified yet."
      redirect_to :root
      return
    end
  end
end

app/views/rushees/_form.html.erb
<%= form_for @rushee, :html => {:class => "form-horizontal"} do |f| %>
    <%# render 'shared/rushee_error_messages' %>
    <%= f.text_field :firstname, :class => 'form-control', :placeholder => "First name" %>
    <%= f.text_field :lastname, :class => 'form-control', :placeholder => "Last name" %>
    <%= f.text_field :email, :class => 'form-control', :placeholder => "Email address" %>
    <%= f.text_field :cellphone, :class => 'form-control', :placeholder => "Cell phone" %>
    <%= f.text_field :facebook_url, :class => 'form-control', :placeholder => "Facebook URL"%>
    <%= f.text_field :twitter_url, :class => 'form-control', :placeholder => "Twitter URL"%>
    <div class="form-group">
      <label for="profileFile">Profile Picture</label>
      <%= f.file_field :profile_picture_url, :id => "profileFile" %>
      <p class="help-block">Upload a picture for them</p>
    </div>
    <%= f.text_field :dorm, :class => 'form-control', :placeholder => "Dorm"%>
    <%= f.text_field :room_number, :class => 'form-control', :placeholder => 'Room number' %>
    <%= f.text_field :hometown, :class => 'form-control', :placeholder => "Hometown" %>
    <%= f.text_field :sports, :class => 'form-control', :placeholder => "Sports" %>
    <%= f.text_field :frats_rushing, :class => 'form-control', :placeholder => "Cross rushing with" %>
    <%= f.text_field :primary_contact_brother, :class => 'form-control', :placeholder => "Primary contact brother" %>


  <div class="actions">
    <%= f.submit :class => "btn"%>
  </div>
<% end %>

app/views/rushees/_form_edit.html.erb
<%= form_for @rushee, :html => {:class => "form-horizontal"} do |f| %>
    <%= render 'shared/rushee_error_messages' %>
    First Name <%= f.text_field :firstname, :class => 'form-control', :placeholder => "First name" %>
    Last Name <%= f.text_field :lastname, :class => 'form-control', :placeholder => "Last name" %>
    Email <%= f.text_field :email, :class => 'form-control', :placeholder => "Email address" %>
    Cell Phone <%= f.text_field :cellphone, :class => 'form-control', :placeholder => "Cell phone" %>
    Facebook URL <%= f.text_field :facebook_url, :class => 'form-control', :placeholder => "Facebook URL"%>
    Twitter URL <%= f.text_field :twitter_url, :class => 'form-control', :placeholder => "Twitter URL"%>
    <br>
    <div class="form-group">
      <label for="profileFile">Profile Picture</label>
      <%= f.file_field :picture, :id => "profileFile" %>
      <p class="help-block">Upload a picture for them</p>
    </div>
    Dorm <%= f.text_field :dorm, :class => 'form-control', :placeholder => "Dorm"%>
    Room Number <%= f.text_field :room_number, :class => 'form-control', :placeholder => 'Room number' %>
    Home Town <%= f.text_field :hometown, :class => 'form-control', :placeholder => "Hometown" %>
    Sports <%= f.text_field :sports, :class => 'form-control', :placeholder => "Sports" %>
    Cross rushing with <%= f.text_field :frats_rushing, :class => 'form-control', :placeholder => "Cross rushing with" %>
    Primary Contact:  <%= f.collection_select(:primary_contact_id, Brother.findAllByFraternityID(current_brother.fraternity.id), :id, :firstname, include_blank: true) %> <br>
    Action Status:  <%= f.select(:action_status, @rushee.validActionSelectStatuses) %> <br>
    Bid Status:  <%= f.select(:bid_status, @rushee.validBidSelectStatuses) %> <br>


    

  <div class="actions">
    <%= f.submit :class => "btn"%>
  </div>
<% end %>

app/views/rushees/_form_new.html.erb
<%= form_for @rushee, :html => {:class => "form-horizontal"} do |f| %>
    <%= render 'shared/rushee_error_messages' %>
    <%= f.hidden_field :fraternity_id, :value => current_brother.fraternity_id %>
    <%= f.hidden_field :action_status, :value => "None" %>
    <%= f.hidden_field :bid_status, :value => "None" %>
    First Name <%= f.text_field :firstname, :class => 'form-control', :placeholder => "First name" %>
    Last Name <%= f.text_field :lastname, :class => 'form-control', :placeholder => "Last name" %>
    Email <%= f.text_field :email, :class => 'form-control', :placeholder => "Email address" %>
    Cell Phone <%= f.text_field :cellphone, :class => 'form-control', :placeholder => "Cell phone" %>
    Facebook URL <%= f.text_field :facebook_url, :class => 'form-control', :placeholder => "Facebook URL"%>
    Twitter URL <%= f.text_field :twitter_url, :class => 'form-control', :placeholder => "Twitter URL"%>
    <div class="form-group">
      <label for="profileFile">Profile Picture</label>
      <%= f.file_field :picture, :id => "profileFile" %>
      <p class="help-block">Upload a picture for them</p>
    </div>
    Dorm <%= f.text_field :dorm, :class => 'form-control', :placeholder => "Dorm"%>
    Room Number <%= f.text_field :room_number, :class => 'form-control', :placeholder => 'Room number' %>
    Home Town <%= f.text_field :hometown, :class => 'form-control', :placeholder => "Hometown" %>
    Sports <%= f.text_field :sports, :class => 'form-control', :placeholder => "Sports" %>
    Cross rushing with <%= f.text_field :frats_rushing, :class => 'form-control', :placeholder => "Cross rushing with" %>
    Primary Contact: <%= f.collection_select(:primary_contact_id, Brother.findAllByFraternityID(current_brother.fraternity.id), :id, :firstname, include_blank: true) %>

  <div class="actions">
    <%= f.submit :class => "btn"%>
  </div>
<% end %>

app/views/rushees/edit.html.erb
<h1 class>Editing Rushee</h1>
<div class="form-container">
  <%= render 'form_edit' %>
</div>

app/views/rushees/index.html.erb
<p><%= link_to "New Rushee", new_rushee_path %></p>
<ul class="rushees">
    <% @rushees.each do |rushee| %>
      <li>
        <div class="rushee-outer">
          <%= image_tag(rushee.picture.url(:medium), class: "rushee-image") %>
            <div class="rushee-hover hideable">
              <%= link_to rushee_path(rushee) do %>
                <p class="rushee-name"><%= "#{rushee.firstname} #{rushee.lastname}" %></p>
              <% end %>
              <i class="fa fa-check fa-2x overlay-btn" data-rushee-id=<%= rushee.id %> ></i>
              <i class="fa fa-arrow-up fa-2x overlay-btn" data-rushee-id=<%= rushee.id %> ></i>
            </div>
        </div>
      </li>
    <% end %>
</ul>

<table  border="0">
  <tr>
  <td valign="top">
    <h3>Rush Action Feed</h3>
    <% loopd = 0 %>
    <% @actions.reverse_each do |action| %>
      <p><%= link_to action.description, rushee_path(action.rushee_id) %> (<%= time_ago_in_words(action.created_at) %> ago)</p>
      <% loopd = loopd + 1 %>
      <% break if loopd >= @max_feed %>
    <% end %>
  </td>
</tr>
</table>

app/views/rushees/new.html.erb
<h1 class>A new rushee!</h1>
<div class="form-container">
	<%= render 'form_new' %>
</div>

app/views/rushees/present.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presentation</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body id="presentationScreen">
      <table id="presentationTable">
        <tr>
          <td></td>
          <td id="exitCell">
            <%= link_to "Exit", rushees_path %>
          </td>
        </tr>
        <% if @rushees.any? %>
          <% rushee = @rushees.first %>
        <tr>
          <td id="pictureCell">
            <div id="picture-holder">
	            <%= image_tag rushee.picture.url(:medium), id: "slideImage" %>
            </div>
          </td>
          <td id="informationCell" data-id="" data-rails-id="">
              <%= link_to "#{rushee.firstname} #{rushee.lastname}", rushee_path(rushee), id: "slideName" %><br /><br />
              <p>
                Email: <span id="slideEmail"><%= rushee.email %></span><br />
                Primary Contact: <span id="slidePrimary"><%= rushee.primaryContactName %></span><br />
                Phone Number: <span id="slidePhone"><%= rushee.cellphone %></span><br />
                Facebook Page:  <span id="slidefaceBook"><%= rushee.facebook_url %></span><br />
                Dorm: <span id="slideDorm"><%= rushee.dorm %></span><br />
                Hometown: <span id="slideHometown"><%= rushee.hometown %></span><br />
                Sports: <span id="slideSports"><%= rushee.sports %></span><br />
                Also Rushing: <span id="slideCompetingFrats"><%= rushee.frats_rushing %></span><br /><br />
                
                Action Status: <span id="slideActionStatus"><%= rushee.action_status %></span><br />
                Bid?  <span id="slideBidStatus"><%= rushee.bid_status %></span>
              </p>                            
          </td>
        </tr>
        <% else %>
          No Rushees at this time.
        <% end %>  
        <tr id="slideNavRow">
          <td><a id="lastSlide" href="#">Back</a></td>
          <td><a id="nextSlide" href="#">Next</a></td>
      <table>    
  </body>

</html>
<script type="text/javascript">
  slideShow();
</script>

app/views/rushees/show.html.erb
<table width="800px">
<table width="1000px">
  <tr>
    <td span="2">
      <h1 class="rushee_name"><%= "#{@rushee.firstname} #{@rushee.lastname}" %></h1>
    </td>
  </tr>
  <tr>
    <td valign="top">
        <% if @rushee.picture? %>
          <div id="picture-holder2">
            <%= image_tag @rushee.picture.url(:medium) %>
          </div>
        <% else %>
          <div id="picture-holder">
            <%= image_tag @rushee.picture.url(:medium) %>
          </div>
        <% end %>
        
    </td>
    
    <td valign="top">
      <table class="table">
        <tr><td>Primary Contact</td>
          <td>
          <% if @rushee.primary_contact %>
            <a href="/accounts/detail/<%= @rushee.primary_contact.id %>"><%= @rushee.primaryContactName %></a>
          <% else %>
            <%= @rushee.primaryContactName %>
          <% end %>
        </td></tr>
        <tr><td>Cellphone</td><td><%= @rushee.cellphone %></td></tr>
        <tr><td>Dorm & Room Number</td><td><%= @rushee.dorm + " " + @rushee.room_number %></td></tr>
        <tr><td>Sports</td><td><%= @rushee.sports %></td></tr>
        <tr><td>Cross Rushing</td><td><%= @rushee.frats_rushing %></td></tr>
        <tr><td>Home Town</td><td><%= @rushee.hometown %></td></tr>
        <tr><td>Email</td><td><%= @rushee.email %></td></tr>
        <tr><td>Action Status</td><td><%= @rushee.action_status %></td></tr>
        <tr><td>Bid Status</td><td><%= @rushee.bid_status %></td></tr>

      </table>
    </td>

    <% if @rushee.events %>
      <td valign="top">
        <table class="table">
          <tr><th>Event</th><th>Date</th></tr>
          <% @rushee.events.each do |event| %>
            <tr><td><%= link_to event.name, event_path(event) %></td><td><%= event.date.strftime("%d-%m-%Y") %></td></tr>
          <% end %>
        </table>
      </td>
    <% end %>

  </tr>
</table>

<p>
  <table>
    <tr>
      <td> Met <%= @rushee.metBrotherCount %> Brothers </td>
      <td> 
        <%= button_to "Met", meet_rushee_path, method: "post", class: "btn btn-success" %>        
      </td>
      <td>
        <%= button_to "Haven't Met", unmeet_rushee_path, method: "post", class: "btn btn-danger" %>   
      </td>
    </tr>
    <tr>
      <td> Has <%= @rushee.upVoteCount %> Votes </td>
      <td> 
        <%= button_to "Upvote", upVote_rushee_path, method: "post", class: "btn btn-success" %>        
      </td>
      <td>
        <%= button_to "Remove Vote", removeVote_rushee_path, method: "post", class: "btn btn-danger" %>   
      </td>
    </tr>   
  </table>
</p>

<h3>Edit Information</h3>
<%= link_to 'Edit ' + @rushee.full_name, edit_rushee_path(@rushee) %>

<% if current_brother.is_admin %>
  <h3>Administrator Controls</h3>
  <%= link_to "Delete #{@rushee.firstname} #{@rushee.lastname}", @rushee, :method => :delete, :title => "Delete rushee", data: {confirm: "Delete #{@rushee.firstname} #{@rushee.lastname}?"} %>
<% end %>

<h3>Comments</h3>
<div class="comments-container">
  <table class="table">
  <tr>
    <td>
    <%= form_tag( { :action => :comment }, { :method => :post }) %>
      
      
        <input type="hidden" name="id" value="<%= @rushee.id %>">
        <textarea style="width:450px;height:100px;" name="text"></textarea><br/>
        <input type="submit" value="Post Comment">
      </form>
    
    </td>
  </tr>
  <% if @comments.length > 0 %>
      <% @comments.reverse_each do |comment| %>
        <tr>
          <td>
            <a href="/accounts/detail/<%= comment.brother.id %>"><%= comment.brother.firstname + " " + comment.brother.lastname %></a> said <%= time_ago_in_words(comment.created_at) %> ago: <br/><br/><%= comment.text %>
          </td>
        </tr>
      <% end %>
    
  <% else %>
    <tr>
      <td>No comments yet.</td>
    </tr>
  <% end %>
  </table>
</div>