config/routes.rb
Djsmiley0LourdBshaibuMattyhkFinal::Application.routes.draw do
  
  resources :rushees do
    member do
      post :upVote
      post :removeVote
      post :meet
      post :unmeet
      get  :getApproval
    end
  end
  resources :actions
  resources :events

  root :to => "rushees#index"
  
  post "rushees/comment" => "rushees#comment"
  post "events/addRushee" => "events#addRushee"

  get "accounts/" => "accounts#index"
  get "accounts/detail/:id" => "accounts#detail"
  get "accounts/verify/:id" => "accounts#verify" 
  get "accounts/deny/:id" => "accounts#deny" 
  get "accounts/invite"
  post "accounts/invite" => "accounts#processInvite"
  devise_for :brothers

  match '/presentation', to: 'rushees#present', via: 'get'

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-top" role="navigation">
  <div class="navbar-header">
    
  </div>
    <a class="navbar-brand" <%= link_to "RUSHtracker", rushees_path %></a>
      <ul class="nav navbar-nav navbar-left">
        <% if current_brother %>
          <!--<li><p class="navbar-text"><%= "Logged in as #{current_brother.firstname} #{current_brother.lastname} "%></p></li>-->
          <li><p class="navbar-text"><%= link_to "Rushees", rushees_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Presentation", presentation_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Brothers", accounts_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Events", events_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Reminders", new_action_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Settings", edit_brother_registration_path %></p></li>
          <li><p class="navbar-text"><%= link_to "Sign out", destroy_brother_session_path, :method => :delete %></p></li>
        <% else %>
          <li><p class="navbar-text pull-right"><%= link_to "Sign In", new_brother_session_path %></p></li>
          <li><p class="navbar-text pull-right"><%= link_to "Sign Up", new_brother_registration_path %></p></li>
        <% end %>
      </ul>                
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RUSH Tracker</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet" type="text/css">
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="my-container">
        <%= yield %>
      </div>
  </body>
</html>